### ISSUE TITLE
Looking to use this as a potential API for my superuser data management plugin

### ISSUE THREAD

**Issue by MeepTech** [OPD-libs/OPD-libs#22]
Hey there! I was originally looking at using `metaedit` but was suggested this way for an api to edit metadata and was looking at using this as a dependency of my plugin here:
https://github.com/Meep-Tech/obsidian-metadata-scry-plugin

I just wanted to open up a dialog here about compatibility potentiality and when a plugin version of the opd-metadata-lib would maybe be available to test with. 

Thank you!

**Comment by mProjectsCode** [comment]
you can test with the already released version, I have already updated one of my plugins to use the metadata lib, but you should wait until we release version 0.0.3 which adds some missing methods to the pubic part of the API. Technically you can access those methods already, but that isn't optimal.

The updated branch of one of my plugins:
https://github.com/mProjectsCode/obsidian-meta-bind-plugin/tree/metadata-lib

Since i have time this evening, I will probably release version 0.0.3 in a few hours. The methods are already implemented, but doc-comments are still missing.

The methods in question
https://github.com/OPD-libs/OPD-libs/blob/0bba7c1aa2036c1e7e7fa0db4f4cdcac78aab063/libs/OPD-metadata-lib/src/API.ts#L137
and
https://github.com/OPD-libs/OPD-libs/blob/0bba7c1aa2036c1e7e7fa0db4f4cdcac78aab063/libs/OPD-metadata-lib/src/API.ts#L141

**Comment by MeepTech** [comment]
Ah I see! I was very confused by the file being named Internal and being replaced by the Api file in the docs. I figured I shouldn't look at the 'internals' of another library if it's an api haha.

Thanks so much for the example and the super quick reply!

**Comment by mProjectsCode** [comment]
Version 0.0.3 should be released now

**Comment by MeepTech** [comment]
Thanks! I've updated my library some as well. Here is a link to the api implementation im developing. it's basically just designed to make all the functionality you've worked on available in quick shorthand form for quick typing on any keyboard:

https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/api.ts#L454

https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/api.ts#L606

(access able here: https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/api.ts#L1547 and here:https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/api.ts#L816)

also compressed into:
these 3 functions
https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/api.ts#L1262 

and these 3 functions
https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/api.ts#L1563

**Comment by mProjectsCode** [comment]
Oh wow that is quite the long file

**Comment by MeepTech** [comment]
> Oh wow that is quite the long file

Good point! I've taken that into account and sliced it into smaller files that are easier to parse.
Here are the updated links if you want them!

#### Full API objects:
https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/types/editor.ts#L15
https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/types/editor.ts#L160

(accessable on my main api here: https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/types/scrier.ts#L72
    and here: https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/types/current.ts#L220)

#### Compressed Api Functions
these 3 functions:
https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/types/scrier.ts#L518
and these 3 functions:
https://github.com/Meep-Tech/obsidian-metadata-scry-plugin/blob/master/src/types/current.ts#L248


Thanks so much for the constructive comment!

**Comment by MeepTech** [comment]
I'm not developing this actively anymore so i'll close this
